channels:
- conda-forge
- zoq
dependencies:
# Jupyter
- jupyterlab=3
- jupyter-offlinenotebook=0.2
- nodejs
- nbconvert=6
# Python Kernel
- ipykernel=5.1
- xeus-python
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.13
- altair=4.1
- bqplot=0.12.20
- dask=2020.12
- matplotlib
- pandas
- python
- scikit-image
- scikit-learn
- seaborn
- sympy
- pyyaml
- traittypes==0.2.1
- invoke=1.2
- pandas-datareader
- plotly
- imbalanced-learn=0.8.0
# C++ Kernel
- xeus-cling
- xtensor
- xwidgets
- xframe
# R Kernel
- r-base=4.1.0
- r-ggplot2
- r-irkernel
# mlpack
- c-compiler
- cxx-compiler
- armadillo=9
- cereal
- cmake
- boost-cpp
- openblas
- openmp
- setuptools
- cython
- numpy
- pandas
- gxx_linux-64=9.3.0
- ensmallen
# SoS
- sos-notebook
- jupyterlab-sos
- sos-papermill
- folium
