name = "mlpack"
uuid = "cf18a64e-e90e-11e8-37b7-fb5df6478bc0"
author = ["mlpack developers <mlpack@lists.mlpack.org>"]
version = "3.3.2"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
mlpack_jll = "156a7db3-27ba-586e-a86b-f061da4f95ea"

[compat]
julia = "1.3"
mlpack_jll = "3.3.2"
